# Generated by Django 4.2.7 on 2025-04-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="google_id",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="microsoft_id",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
