# Generated by Django 4.2.7 on 2025-04-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usermodel_google_id_usermodel_microsoft_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="enable_2fa",
            field=models.BooleanField(default=False),
        ),
    ]
