# Generated by Django 4.2.7 on 2025-04-03 12:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.base.base_model


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_settings", "0003_twofactorsettingmodel_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryLoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=core.base.base_model.make_object_id,
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("is_used", models.BooleanField(default=False)),
                ("type", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uid"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="user_settin_created_0e0ba3_idx"
                    )
                ],
            },
        ),
    ]
